import type { QueryResponse } from "../api/types";

/**
 * [OFFICIAL SOURCE] Renders `answer_text` exactly as returned - never
 * paraphrased, summarized, or "helped along" by frontend logic. When
 * `answer_text` is null (ABSTAIN/ESCALATE/UPSTREAM_BLOCKED/failure), this
 * panel explicitly says no answer was produced rather than inventing one
 * (docs "EVIDENCE-FIRST UX": "If the backend returns no valid evidence or
 * abstains, the UI must clearly communicate that instead of attempting to
 * produce a helpful-looking answer from frontend logic").
 */
export function AnswerPanel({ response }: { response: QueryResponse }) {
  return (
    <section className="panel answer-panel" aria-labelledby="answer-heading">
      <h2 id="answer-heading">Answer</h2>
      {response.answer_text ? (
        <>
          <p className="answer-text" lang={response.answer_language ?? undefined}>
            {response.answer_text}
          </p>
          <p className="answer-meta">
            {response.answer_language ? `Language: ${response.answer_language}` : null}
            {response.translation_applied ? " (translated)" : null}
            {response.provider_name ? ` - generated by: ${response.provider_name}` : null}
          </p>
        </>
      ) : (
        <p className="answer-empty">
          No grounded answer was produced for this query. See the status and evidence sections below for why.
        </p>
      )}
    </section>
  );
}
